import type { Product, Location, AnalyticsData, Language, Translations, StoreLayout, Aisle } from './types';

export const INITIAL_LOCATIONS: Location[] = [
  { id: 1, floor: 1, aisleId: 3, shelf: 2, bin: 1 },
  { id: 2, floor: 1, aisleId: 3, shelf: 2, bin: 2 },
  { id: 3, floor: 1, aisleId: 5, shelf: 1, bin: 4 },
  { id: 4, floor: 2, aisleId: 101, shelf: 4, bin: 3 },
  { id: 5, floor: 2, aisleId: 102, shelf: 3, bin: 5 },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 1,
    name: { ar: 'تفاح أحمر', fr: 'Pomme Rouge', de: 'Roter Apfel' },
    category: { ar: 'فواكه', fr: 'Fruits', de: 'Obst' },
    description: { ar: 'تفاح أحمر طازج ومقرمش.', fr: 'Pommes rouges fraîches et croquantes.', de: 'Frische und knackige rote Äpfel.' },
    barcode: '1234567890123',
    price: 2.99,
    stock: 150,
    locationId: 1,
    imageUrl: 'https://images.unsplash.com/photo-1579613832125-5d34a13ffe2a?w=200',
  },
  {
    id: 2,
    name: { ar: 'خبز', fr: 'Pain', de: 'Brot' },
    category: { ar: 'مخبز', fr: 'Boulangerie', de: 'Bäckerei' },
    description: { ar: 'خبز طازج مخبوز يومياً.', fr: 'Pain frais cuit quotidiennement.', de: 'Täglich frisch gebackenes Brot.' },
    barcode: '2345678901234',
    price: 1.50,
    stock: 8,
    locationId: 3,
    imageUrl: 'https://images.unsplash.com/photo-1534620808146-d336b362675c?w=200',
  },
  {
    id: 3,
    name: { ar: 'حليب', fr: 'Lait', de: 'Milch' },
    category: { ar: 'ألبان', fr: 'Produits laitiers', de: 'Molkereiprodukte' },
    description: { ar: 'حليب كامل الدسم غني بالكالسيوم.', fr: 'Lait entier riche en calcium.', de: 'Vollmilch reich an Kalzium.' },
    barcode: '3456789012345',
    price: 1.20,
    stock: 0,
    locationId: 2,
    imageUrl: 'https://images.unsplash.com/photo-1620189507195-68309c04c4d5?w=200',
  },
  {
    id: 4,
    name: { ar: 'بيض', fr: 'Œufs', de: 'Eier' },
    category: { ar: 'ألبان', fr: 'Produits laitiers', de: 'Molkereiprodukte' },
    description: { ar: 'بيض طازج من المزرعة.', fr: 'Œufs frais de la ferme.', de: 'Frische Eier vom Bauernhof.' },
    barcode: '4567890123456',
    price: 3.50,
    stock: 5,
    locationId: 5,
    imageUrl: 'https://images.unsplash.com/photo-1587486913049-53fc889896cf?w=200',
  },
];

const INITIAL_AISLES_FLOOR_1: Aisle[] = [
  { id: 1, name: 'Aisle 1', x: 40, y: 30, width: 30, height: 180, orientation: 'vertical', shelves: 5 },
  { id: 2, name: 'Aisle 2', x: 100, y: 30, width: 30, height: 180, orientation: 'vertical', shelves: 5 },
  { id: 3, name: 'Aisle 3', x: 160, y: 30, width: 30, height: 180, orientation: 'vertical', shelves: 5 },
  { id: 4, name: 'Aisle 4', x: 220, y: 30, width: 30, height: 180, orientation: 'vertical', shelves: 5 },
  { id: 5, name: 'Frozen Foods', x: 280, y: 30, width: 80, height: 30, orientation: 'horizontal', shelves: 2 },
  { id: 6, name: 'Bakery', x: 280, y: 180, width: 80, height: 30, orientation: 'horizontal', shelves: 1 },
];

const INITIAL_AISLES_FLOOR_2: Aisle[] = [
  { id: 101, name: 'Electronics', x: 50, y: 50, width: 100, height: 40, orientation: 'horizontal', shelves: 3 },
  { id: 102, name: 'Home Goods', x: 50, y: 120, width: 100, height: 40, orientation: 'horizontal', shelves: 4 },
  { id: 103, name: 'Clothing', x: 200, y: 50, width: 40, height: 150, orientation: 'vertical', shelves: 5 },
];


export const INITIAL_STORE_LAYOUT: StoreLayout = {
  floors: [
    { floorNumber: 1, aisles: INITIAL_AISLES_FLOOR_1, entranceX: 200, entranceY: 290 },
    { floorNumber: 2, aisles: INITIAL_AISLES_FLOOR_2, entranceX: 200, entranceY: 290 },
  ],
  storeWidth: 400,
  storeHeight: 300,
};

export const INITIAL_ANALYTICS: AnalyticsData = {
  topSearches: [
    { term: 'Pain', count: 120 },
    { term: 'Lait', count: 95 },
    { term: 'Eggs', count: 80 },
    { term: 'Apples', count: 72 },
    { term: 'Water', count: 50 },
  ],
  peakTimes: [
    { hour: '09:00', searches: 30 },
    { hour: '11:00', searches: 80 },
    { hour: '13:00', searches: 60 },
    { hour: '15:00', searches: 75 },
    { hour: '17:00', searches: 110 },
    { hour: '19:00', searches: 90 },
  ],
  missingItems: [
    { productId: 3, reportCount: 15 },
    { productId: 1, reportCount: 5 },
  ],
};

export const TRANSLATIONS: Record<Language, Translations> = {
  ar: {
    dashboard: "لوحة التحكم",
    products: "المنتجات",
    locations: "المواقع",
    analytics: "التحليلات",
    search: "بحث",
    storeLayout: "تخطيط المتجر",
    arabic: "العربية",
    french: "الفرنسية",
    german: "الألمانية",
    productManagement: "إدارة المنتجات",
    addProduct: "إضافة منتج",
    scanProduct: "مسح المنتج",
    scanProductQRCode: "مسح رمز الاستجابة السريعة للمنتج",
    productName: "اسم المنتج",
    category: "الفئة",
    price: "السعر",
    stock: "المخزون",
    location: "الموقع",
    editProduct: "تعديل المنتج",
    description: "الوصف",
    barcode: "الرمز الشريطي",
    imageURL: "رابط الصورة",
    generateWithAI: "إنشاء بالذكاء الاصطناعي",
    cancel: "إلغاء",
    save: "حفظ",
    deleteProduct: "حذف المنتج",
    confirmDelete: "هل أنت متأكد أنك تريد حذف هذا المنتج؟ لا يمكن التراجع عن هذا الإجراء.",
    delete: "حذف",
    aisle: "ممر",
    shelf: "رف",
    floor: "طابق",
    bin: "صندوق",
    locationManagement: "إدارة المواقع",
    addLocation: "إضافة موقع",
    editLocation: "تعديل الموقع",
    deleteLocation: "حذف الموقع",
    confirmDeleteLocation: "هل أنت متأكد أنك تريد حذف هذا الموقع؟ سيتم إلغاء تعيين جميع المنتجات في هذا الموقع.",
    reportsAndAnalytics: "التقارير والتحليلات",
    totalProducts: "إجمالي المنتجات",
    outOfStock: "نفد من المخزون",
    mostSearched: "الأكثر بحثًا",
    topSearches: "أهم عمليات البحث",
    searchCount: "عدد البحث",
    peakTimes: "أوقات الذروة",
    customerSearch: "بحث العملاء",
    searchForProduct: "ابحث عن منتج...",
    searchResult: "نتيجة البحث",
    productNotFound: "لم يتم العثور على المنتج.",
    productLocation: "موقع المنتج",
    directions: "الاتجاهات",
    generatingDirections: "جاري إنشاء الاتجاهات...",
    yourLocation: "موقعك",
    productIsHere: "المنتج هنا",
    filterByCategory: "تصفية حسب الفئة",
    filterByStock: "تصفية حسب حالة المخزون",
    filterByLocation: "تصفية حسب الموقع",
    all: "الكل",
    inStock: "متوفر",
    clearFilters: "مسح المرشحات",
    lowStockThreshold: "حد المخزون المنخفض",
    lowStockItems: "منتجات ذات مخزون منخفض",
    lowStockProducts: "المنتجات ذات المخزون المنخفض",
    stockRemaining: "المخزون المتبقي",
    layoutConfiguration: "تهيئة التخطيط",
    layoutPreview: "معاينة التخطيط",
    aisleName: "اسم الممر",
    orientation: "الاتجاه",
    positionX: "الموضع X",
    positionY: "الموضع Y",
    width: "العرض",
    height: "الارتفاع",
    shelves: "رفوف",
    addAisle: "إضافة ممر",
    editAisle: "تعديل الممر",
    deleteAisle: "حذف الممر",
    confirmDeleteAisle: "هل أنت متأكد أنك تريد حذف هذا الممر؟",
    vertical: "عمودي",
    horizontal: "أفقي",
    storeWidth: "عرض المتجر",
    storeHeight: "ارتفاع المتجر",
    aisleConfiguration: "تهيئة الممر",
    manageFloors: "إدارة الطوابق",
    addFloor: "إضافة طابق",
    deleteFloor: "حذف الطابق",
    confirmDeleteFloor: "هل أنت متأكد أنك تريد حذف هذا الطابق وجميع ممراته؟",
    entrancePosition: "موضع المدخل",
    entranceX: "المدخل X",
    entranceY: "المدخل Y",
    typeToSearch: "ابدأ بالكتابة للبحث عن منتج.",
  },
  fr: {
    dashboard: "Tableau de Bord",
    products: "Produits",
    locations: "Emplacements",
    analytics: "Analyses",
    search: "Recherche",
    storeLayout: "Configuration du Magasin",
    arabic: "Arabe",
    french: "Français",
    german: "Allemand",
    productManagement: "Gestion des Produits",
    addProduct: "Ajouter un Produit",
    scanProduct: "Scanner un Produit",
    scanProductQRCode: "Scanner le code QR du produit",
    productName: "Nom du Produit",
    category: "Catégorie",
    price: "Prix",
    stock: "Stock",
    location: "Emplacement",
    editProduct: "Modifier le Produit",
    description: "Description",
    barcode: "Code-barres",
    imageURL: "URL de l'image",
    generateWithAI: "Générer avec l'IA",
    cancel: "Annuler",
    save: "Enregistrer",
    deleteProduct: "Supprimer le Produit",
    confirmDelete: "Êtes-vous sûr de vouloir supprimer ce produit ? Cette action est irréversible.",
    delete: "Supprimer",
    aisle: "Allée",
    shelf: "Étagère",
    floor: "Étage",
    bin: "Casier",
    locationManagement: "Gestion des Emplacements",
    addLocation: "Ajouter un Emplacement",
    editLocation: "Modifier l'Emplacement",
    deleteLocation: "Supprimer l'Emplacement",
    confirmDeleteLocation: "Êtes-vous sûr de vouloir supprimer cet emplacement ? Tous les produits à cet emplacement ne seront plus assignés.",
    reportsAndAnalytics: "Rapports et Analyses",
    totalProducts: "Total des Produits",
    outOfStock: "En Rupture de Stock",
    mostSearched: "Le plus Recherché",
    topSearches: "Top Recherches",
    searchCount: "Nombre de recherches",
    peakTimes: "Heures de Pointe",
    customerSearch: "Recherche Client",
    searchForProduct: "Rechercher un produit...",
    searchResult: "Résultat de la recherche",
    productNotFound: "Produit non trouvé.",
    productLocation: "Emplacement du produit",
    directions: "Itinéraire",
    generatingDirections: "Génération de l'itinéraire...",
    yourLocation: "Votre Emplacement",
    productIsHere: "Le produit est ici",
    filterByCategory: "Filtrer par catégorie",
    filterByStock: "Filtrer par statut du stock",
    filterByLocation: "Filtrer par emplacement",
    all: "Tous",
    inStock: "En stock",
    clearFilters: "Effacer les filtres",
    lowStockThreshold: "Seuil de stock bas",
    lowStockItems: "Articles à stock bas",
    lowStockProducts: "Produits à stock bas",
    stockRemaining: "Stock restant",
    layoutConfiguration: "Configuration de l'agencement",
    layoutPreview: "Aperçu de l'agencement",
    aisleName: "Nom de l'allée",
    orientation: "Orientation",
    positionX: "Position X",
    positionY: "Position Y",
    width: "Largeur",
    height: "Hauteur",
    shelves: "Étagères",
    addAisle: "Ajouter une allée",
    editAisle: "Modifier l'allée",
    deleteAisle: "Supprimer l'allée",
    confirmDeleteAisle: "Êtes-vous sûr de vouloir supprimer cette allée ?",
    vertical: "Verticale",
    horizontal: "Horizontale",
    storeWidth: "Largeur du magasin",
    storeHeight: "Hauteur du magasin",
    aisleConfiguration: "Configuration de l'allée",
    manageFloors: "Gérer les étages",
    addFloor: "Ajouter un étage",
    deleteFloor: "Supprimer l'étage",
    confirmDeleteFloor: "Êtes-vous sûr de vouloir supprimer cet étage et toutes ses allées ?",
    entrancePosition: "Position de l'entrée",
    entranceX: "Entrée X",
    entranceY: "Entrée Y",
    typeToSearch: "Commencez à taper pour rechercher un produit.",
  },
  de: {
    dashboard: "Dashboard",
    products: "Produkte",
    locations: "Standorte",
    analytics: "Analytik",
    search: "Suche",
    storeLayout: "Ladenlayout",
    arabic: "Arabisch",
    french: "Französisch",
    german: "Deutsch",
    productManagement: "Produktmanagement",
    addProduct: "Produkt hinzufügen",
    scanProduct: "Produkt scannen",
    scanProductQRCode: "Produkt-QR-Code scannen",
    productName: "Produktname",
    category: "Kategorie",
    price: "Preis",
    stock: "Lager",
    location: "Standort",
    editProduct: "Produkt bearbeiten",
    description: "Beschreibung",
    barcode: "Barcode",
    imageURL: "Bild-URL",
    generateWithAI: "Mit KI generieren",
    cancel: "Abbrechen",
    save: "Speichern",
    deleteProduct: "Produkt löschen",
    confirmDelete: "Sind Sie sicher, dass Sie dieses Produkt löschen möchten? Diese Aktion kann nicht rückgängig gemacht werden.",
    delete: "Löschen",
    aisle: "Gang",
    shelf: "Regal",
    floor: "Etage",
    bin: "Fach",
    locationManagement: "Standortmanagement",
    addLocation: "Standort hinzufügen",
    editLocation: "Standort bearbeiten",
    deleteLocation: "Standort löschen",
    confirmDeleteLocation: "Sind Sie sicher, dass Sie diesen Standort löschen möchten? Alle Produkte an diesem Standort werden die Zuweisung verlieren.",
    reportsAndAnalytics: "Berichte & Analytik",
    totalProducts: "Gesamtprodukte",
    outOfStock: "Nicht vorrätig",
    mostSearched: "Meistgesucht",
    topSearches: "Top-Suchen",
    searchCount: "Suchanzahl",
    peakTimes: "Spitzenzeiten",
    customerSearch: "Kundensuche",
    searchForProduct: "Suche nach einem Produkt...",
    searchResult: "Suchergebnis",
    productNotFound: "Produkt nicht gefunden.",
    productLocation: "Produktstandort",
    directions: "Wegbeschreibung",
    generatingDirections: "Wegbeschreibung wird generiert...",
    yourLocation: "Ihr Standort",
    productIsHere: "Produkt ist hier",
    filterByCategory: "Nach Kategorie filtern",
    filterByLocation: "Nach Standort filtern",
    filterByStock: "Nach Lagerstatus filtern",
    all: "Alle",
    inStock: "Auf Lager",
    clearFilters: "Filter zurücksetzen",
    lowStockThreshold: "Niedriger Lagerbestand Schwellenwert",
    lowStockItems: "Artikel mit niedrigem Lagerbestand",
    lowStockProducts: "Produkte mit niedrigem Lagerbestand",
    stockRemaining: "Verbleibender Lagerbestand",
    layoutConfiguration: "Layout-Konfiguration",
    layoutPreview: "Layout-Vorschau",
    aisleName: "Gangname",
    orientation: "Ausrichtung",
    positionX: "Position X",
    positionY: "Position Y",
    width: "Breite",
    height: "Höhe",
    shelves: "Regale",
    addAisle: "Gang hinzufügen",
    editAisle: "Gang bearbeiten",
    deleteAisle: "Gang löschen",
    confirmDeleteAisle: "Sind Sie sicher, dass Sie diesen Gang löschen möchten?",
    vertical: "Vertikal",
    horizontal: "Horizontal",
    storeWidth: "Ladenbreite",
    storeHeight: "Ladenhöhe",
    aisleConfiguration: "Gangkonfiguration",
    manageFloors: "Etagen verwalten",
    addFloor: "Etage hinzufügen",
    deleteFloor: "Etage löschen",
    confirmDeleteFloor: "Sind Sie sicher, dass Sie diese Etage und alle ihre Gänge löschen möchten?",
    entrancePosition: "Eingangsposition",
    entranceX: "Eingang X",
    entranceY: "Eingang Y",
    typeToSearch: "Beginnen Sie zu tippen, um nach einem Produkt zu suchen.",
  },
};