import { GoogleGenAI } from "@google/genai";
import type { Language, Product, Location } from '../types';

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  // This is a fallback for development environments where the key might not be set.
  // In a production environment, the key should always be available.
  console.warn("API_KEY environment variable not set. Gemini API calls will fail.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const languageMap: Record<Language, string> = {
    ar: "Tunisian Arabic",
    fr: "French",
    de: "German"
};

export const generateDescription = async (
  productName: string,
  category: string,
  language: Language
): Promise<string> => {
  if (!API_KEY) {
    return "API key not configured. [Generated by mock service]";
  }

  const langName = languageMap[language];

  const prompt = `
    Write a short, appealing, one-sentence product description for a product in a supermarket.
    Product Name: "${productName}"
    Category: "${category}"
    Language: ${langName}
    The description should be concise and suitable for a mobile app. Do not include the product name in the response.
    `;

  try {
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
    });
    
    // Using response.text as the recommended way to get the text.
    const text = response.text;
    return text.trim();
  } catch (error) {
    console.error("Error calling Gemini API:", error);
    throw new Error("Failed to generate description from AI.");
  }
};

export const generateImage = async (
  productName: string,
  category: string
): Promise<string> => {
  if (!API_KEY) {
    // Return a placeholder image for development without an API key
    return `https://picsum.photos/seed/${encodeURIComponent(productName)}/200/200`;
  }

  const prompt = `A professional, high-quality photograph of "${productName}" from the category "${category}". The product is centered on a clean, plain white background. E-commerce studio shot.`;

  try {
    const response = await ai.models.generateImages({
      model: 'imagen-4.0-generate-001',
      prompt: prompt,
      config: {
        numberOfImages: 1,
        outputMimeType: 'image/jpeg',
        aspectRatio: '1:1',
      },
    });

    const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
    const imageUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
    return imageUrl;
  } catch (error) {
    console.error("Error calling Gemini API for image generation:", error);
    throw new Error("Failed to generate image from AI.");
  }
};

export const searchProducts = async (
  query: string,
  products: Product[],
  language: Language
): Promise<Product | null> => {
  if (!API_KEY) {
    console.warn("API key not set, using local search fallback.");
    const lowerQuery = query.toLowerCase();
    return products.find(p => 
        p.name[language].toLowerCase().includes(lowerQuery) ||
        p.category[language].toLowerCase().includes(lowerQuery) ||
        p.description[language].toLowerCase().includes(lowerQuery)
    ) || null;
  }

  const productListForPrompt = products.map(p => ({ 
      id: p.id, 
      name: p.name[language],
      category: p.category[language],
      description: p.description[language]
    }));

  const prompt = `
    You are an intelligent supermarket search assistant. A user is looking for a product.
    Here is a list of available products with their IDs, names, categories, and descriptions:
    ${JSON.stringify(productListForPrompt, null, 2)}

    The user's search query is: "${query}"

    Consider the product name, category, and description to find the best match for the user's query.
    Which product best matches this query? Please respond with ONLY the numeric ID of the best matching product.
    If no product is a good match, respond with the number 0.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: prompt,
    });
    
    const text = response.text.trim();
    const productId = parseInt(text, 10);
    
    if (!isNaN(productId) && productId > 0) {
      return products.find(p => p.id === productId) || null;
    }
    
    return null;
  } catch (error) {
    console.error("Error calling Gemini API for search:", error);
    throw new Error("Failed to search for product with AI.");
  }
};

type DirectionsLocation = {
    floor: number;
    aisle: string;
    shelf: number;
    bin: number;
}

export const generateDirections = async (
  location: DirectionsLocation,
  language: Language
): Promise<string> => {
  if (!API_KEY) {
    // Mock response for development
    return `1. Proceed to ${location.aisle}.\n2. Find Shelf ${location.shelf}.\n3. Your item is located in Bin ${location.bin}.`;
  }
  const langName = languageMap[language];

  const prompt = `
    You are a helpful in-store navigation assistant.
    Provide simple, clear, step-by-step directions for a customer to find an item.
    The customer is starting from the main entrance of the store floor.
    The item is at:
    - Floor: ${location.floor}
    - Aisle: ${location.aisle}
    - Shelf: ${location.shelf}
    - Bin: ${location.bin}

    The directions should be in ${langName}.
    Format the output as a numbered list. Be concise and friendly.
  `;

  try {
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
    });
    
    return response.text.trim();
  } catch (error) {
    console.error("Error calling Gemini API for directions:", error);
    throw new Error("Failed to generate directions from AI.");
  }
};
